name: Zip repository and put on S3
on:
  push:
    branches: [ "master" ]

jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          zip -r ./resources.zip ${{ github.workspace }}
      - name: Send ZIP to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload auto_release ./resources.zip
